-- Create colleges table
create table if not exists public.colleges (
  id uuid default uuid_generate_v4() primary key,
  name text not null unique,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.colleges enable row level security;

-- Policies
drop policy if exists "Colleges are viewable by everyone" on public.colleges;
create policy "Colleges are viewable by everyone" on public.colleges for select using (true);

-- Seed Data (West Bengal Colleges)
insert into public.colleges (name, location) values
('Jadavpur University', 'Kolkata'),
('University of Calcutta', 'Kolkata'),
('Indian Institute of Technology Kharagpur', 'Kharagpur'),
('Bengal Engineering and Science University (IIEST)', 'Shibpur'),
('Presidency University', 'Kolkata'),
('St. Xaviers College', 'Kolkata'),
('Scottish Church College', 'Kolkata'),
('Lady Brabourne College', 'Kolkata'),
('Bethune College', 'Kolkata'),
('Asutosh College', 'Kolkata'),
('Maulana Abul Kalam Azad University of Technology', 'Kolkata'),
('Visva-Bharati University', 'Santiniketan'),
('University of Kalyani', 'Kalyani'),
('University of Burdwan', 'Burdwan'),
('Vidyasagar University', 'Midnapore'),
('North Bengal University', 'Siliguri'),
('West Bengal State University', 'Barasat'),
('Rabindra Bharati University', 'Kolkata'),
('Netaji Subhas Open University', 'Kolkata'),
('Aliah University', 'Kolkata'),
('Brainware University', 'Kolkata'),
('Adamas University', 'Barasat'),
('Techno India University', 'Kolkata'),
('Sister Nivedita University', 'Kolkata'),
('Heritage Institute of Technology', 'Kolkata'),
('Institute of Engineering and Management (IEM)', 'Kolkata'),
('Haldia Institute of Technology', 'Haldia'),
('Kalyani Government Engineering College', 'Kalyani'),
('Jalpaiguri Government Engineering College', 'Jalpaiguri'),
('Government College of Engineering and Leather Technology', 'Kolkata'),
('Government College of Engineering and Ceramic Technology', 'Kolkata'),
('RCC Institute of Information Technology', 'Kolkata'),
('Netaji Subhas Engineering College', 'Kolkata'),
('Meghnad Saha Institute of Technology', 'Kolkata'),
('B.P. Poddar Institute of Management and Technology', 'Kolkata'),
('Narula Institute of Technology', 'Kolkata'),
('Gurunanak Institute of Technology', 'Kolkata'),
('Future Institute of Engineering and Management', 'Kolkata'),
('Dr. B.C. Roy Engineering College', 'Durgapur'),
('Asansol Engineering College', 'Asansol'),
('Durgapur Government College', 'Durgapur'),
('Hooghly Mohsin College', 'Chinsurah'),
('Krishnagar Government College', 'Krishnagar'),
('Barasat Government College', 'Barasat'),
('Acharya Prafulla Chandra College', 'New Barrackpore'),
('Bhairab Ganguly College', 'Belgharia'),
('Barrackpore Rastraguru Surendranath College', 'Barrackpore'),
('Rishi Bankim Chandra College', 'Naihati'),
('Dinabandhu Mahavidyalaya', 'Bongaon'),
('Basirhat College', 'Basirhat'),
('Bidhannagar College', 'Salt Lake'),
('Surendranath College', 'Kolkata'),
('City College', 'Kolkata'),
('Bangabasi College', 'Kolkata'),
('Jaipuria College', 'Kolkata'),
('Heramba Chandra College', 'Kolkata'),
('Charuchandra College', 'Kolkata'),
('Jogamaya Devi College', 'Kolkata'),
('Gokhale Memorial Girls College', 'Kolkata'),
('Loreto College', 'Kolkata'),
('Shri Shikshayatan College', 'Kolkata'),
('Bhawanipur Education Society College', 'Kolkata'),
('Goenka College of Commerce and Business Administration', 'Kolkata'),
('Maulana Azad College', 'Kolkata'),
('Victoria Institution', 'Kolkata'),
('Vidyasagar College', 'Kolkata'),
('Maharaja Manindra Chandra College', 'Kolkata'),
('Umesh Chandra College', 'Kolkata'),
('Rani Birla Girls College', 'Kolkata'),
('South Calcutta Girls College', 'Kolkata'),
('Deshbandhu College for Girls', 'Kolkata'),
('Women Christian College', 'Kolkata'),
('Murlidhar Girls College', 'Kolkata'),
('New Alipore College', 'Kolkata'),
('Behala College', 'Kolkata'),
('Vivekananda College', 'Thakurpukur'),
('Prafulla Chandra College', 'Kolkata')
on conflict (name) do nothing;
